apiVersion: v1
kind: Service
metadata:
  name: catalog-db
  namespace: gaming-store
spec:
  clusterIP: None # headless — required for a StatefulSet's stable network identity
  selector:
    app: catalog-db
  ports:
    - port: 3306
      targetPort: 3306
