apiVersion: v1
kind: ConfigMap
metadata:
  name: orders-service-config
  namespace: gaming-store
data:
  APP_NAME: orders-service
  APP_ENV: local
  APP_DEBUG: "true"
  APP_URL: http://localhost:8080
  LOG_CHANNEL: single
  LOG_LEVEL: debug
  DB_CONNECTION: mysql
  DB_HOST: orders-db
  DB_PORT: "3306"
  DB_DATABASE: orders_db
  DB_USERNAME: root
  SESSION_DRIVER: array
  QUEUE_CONNECTION: database
  CACHE_STORE: database
  CATALOG_SERVICE_URL: http://catalog-service
  RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: "5672"
  MAIL_MAILER: log
  JAEGER_OTLP_URL: http://jaeger:4318
