apiVersion: v1
kind: ConfigMap
metadata:
  name: web-bff-config
  namespace: gaming-store
data:
  APP_NAME: web-bff
  APP_ENV: local
  APP_DEBUG: "true"
  APP_URL: http://localhost:8080
  LOG_CHANNEL: stack
  LOG_LEVEL: debug
  DB_CONNECTION: sqlite
  SESSION_DRIVER: file
  QUEUE_CONNECTION: database
  CACHE_STORE: database
  CATALOG_SERVICE_URL: http://catalog-service
  ORDERS_SERVICE_URL: http://orders-service
  USERS_SERVICE_URL: http://users-service
  MAIL_MAILER: log
