<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Third Party Services
    |--------------------------------------------------------------------------
    |
    | This file is for storing the credentials for third party services such
    | as Mailgun, Postmark, AWS and more. This file provides the de facto
    | location for this type of information, allowing packages to have
    | a conventional file to locate the various service credentials.
    |
    */

    'postmark' => [
        'key' => env('POSTMARK_API_KEY'),
    ],

    'resend' => [
        'key' => env('RESEND_API_KEY'),
    ],

    'ses' => [
        'key' => env('AWS_ACCESS_KEY_ID'),
        'secret' => env('AWS_SECRET_ACCESS_KEY'),
        'region' => env('AWS_DEFAULT_REGION', 'us-east-1'),
    ],

    'slack' => [
        'notifications' => [
            'bot_user_oauth_token' => env('SLACK_BOT_USER_OAUTH_TOKEN'),
            'channel' => env('SLACK_BOT_USER_DEFAULT_CHANNEL'),
        ],
    ],

    'jwt_secret' => env('JWT_SECRET'),

    'catalog_service_url' => env('CATALOG_SERVICE_URL', 'http://catalog-service'),
    'orders_service_url' => env('ORDERS_SERVICE_URL', 'http://orders-service'),
    'users_service_url' => env('USERS_SERVICE_URL', 'http://users-service'),

    'jaeger_otlp_url' => env('JAEGER_OTLP_URL', 'http://jaeger:4318'),

    'gemini' => [
        // Google AI Studio key — https://aistudio.google.com/apikey. Never
        // committed; generated manually (unlike JWT_SECRET/
        // INTERNAL_SERVICE_SECRET, an API key can't be auto-generated by
        // scripts/setup-env.sh) — see docs/chatbot.md.
        'api_key' => env('GEMINI_API_KEY'),
        'api_url' => env('GEMINI_API_URL', 'https://generativelanguage.googleapis.com/v1beta'),
        // Flash by default: fast and generously free-tier'd. Override to a
        // Pro model via env if you'd rather trade latency for quality.
        'model' => env('GEMINI_MODEL', 'gemini-3.6-flash'),
    ],

];
