apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-service-config
  namespace: gaming-store
data:
  APP_NAME: catalog-service
  APP_ENV: local
  APP_DEBUG: "true"
  APP_URL: http://localhost:8080
  LOG_CHANNEL: single
  LOG_LEVEL: debug
  DB_CONNECTION: mysql
  DB_HOST: catalog-db
  DB_PORT: "3306"
  DB_DATABASE: catalog_db
  DB_USERNAME: root
  SESSION_DRIVER: array
  QUEUE_CONNECTION: database
  CACHE_STORE: database
  ORDERS_SERVICE_URL: http://orders-service
  MAIL_MAILER: log
  JAEGER_OTLP_URL: http://jaeger:4318
