apiVersion: v1
kind: ConfigMap
metadata:
  name: notifications-service-config
  namespace: gaming-store
data:
  APP_NAME: notifications-service
  APP_ENV: local
  APP_DEBUG: "true"
  LOG_CHANNEL: stderr
  LOG_STDERR_FORMATTER: 'Monolog\Formatter\JsonFormatter'
  LOG_LEVEL: debug
  DB_CONNECTION: sqlite
  RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: "5672"
  MAIL_MAILER: smtp
  MAIL_HOST: smtp.gmail.com
  MAIL_PORT: "587"
  MAIL_FROM_NAME: NextLevelGaming
  JAEGER_OTLP_URL: http://jaeger:4318
  PUSHGATEWAY_URL: http://pushgateway:9091
