name: Deploy Laravel to InfinityFree

on:
  push:
    branches:
      - main  # branche de déploiement

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prepare backend files
        run: |
          mkdir -p deploy-htdocs
          rsync -av --progress ./ deploy-htdocs/ \
            --exclude=vendor/ \
            --exclude=node_modules/ \
            --exclude=.env \
            --exclude=storage/logs/ \
            --exclude=.gitignore \
            --exclude=storage/framework/ \
            --exclude=public/storage

          mkdir -p deploy-htdocs/storage/{logs,framework/{cache,sessions,views},app/public}
          mkdir -p deploy-htdocs/bootstrap/cache
          touch deploy-htdocs/storage/logs/laravel.log
          chmod -R 755 deploy-htdocs/storage deploy-htdocs/bootstrap/cache

      - name: Upload to InfinityFree via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.0
        with:
          server: ${{ secrets.INFINITYFREE_HOST }} # ex: ftpupload.net
          username: ${{ secrets.INFINITYFREE_USERNAME }}
          password: ${{ secrets.INFINITYFREE_PASSWORD }}
          local-dir: ./deploy-htdocs/
          server-dir: /htdocs/
          exclude: |
            .env
            .gitignore
          security: loose
          dry-run: false
